name: Bug report
description: Report a problem or regression
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    id: what_happened
    attributes:
      label: What happened?
      description: Describe the bug and what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: repro_steps
    attributes:
      label: Steps to reproduce
      description: Minimal steps to reproduce the issue.
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version / commit
      description: If known, paste the version or commit SHA.
    validations:
      required: false

